### ISSUE TITLE
Maintenance mode blocks TOTP TFA entry

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/tfa#11]
**Problem/Motivation**
When TFA Rules is enabled, a user trying to reset their password / use a one-time login link is redirected to the TFA setup page.

**Proposed resolution**
I've attached a patch which adds a condition to the rule that the current path is not user/reset.

**Remaining tasks**
This patch needs review. We might also wish to consider adding a rule to redirect to TFA setup once a user has set their own password, though that could be handled in a separate issue as an enhancement.

This is a duplicate of https://www.drupal.org/node/2694723 which is marked as closed/fixed for D7  on 28 October 2023

**Comment by herbdool** [comment]
That commit is now included.
